# Generated by Django 3.2.4 on 2022-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_auto_20220501_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
