# Generated by Django 3.2.4 on 2022-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_tguser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='language',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
