# Generated by Django 3.2.4 on 2022-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_ariza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='body',
            field=models.TextField(),
        ),
    ]
